/* 
 * TODO LIST API
 *
 * exemple d'API REST avec de la documentation
 *
 * OpenAPI spec version: 1.00
 * Contact: frederic.Berton@capgemini.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TodoItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TodoItemTests
    {
        // TODO uncomment below to declare an instance variable for TodoItem
        //private TodoItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TodoItem
            //instance = new TodoItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TodoItem
        /// </summary>
        [Test]
        public void TodoItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TodoItem
            //Assert.IsInstanceOfType<TodoItem> (instance, "variable 'instance' is a TodoItem");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Titre'
        /// </summary>
        [Test]
        public void TitreTest()
        {
            // TODO unit test for the property 'Titre'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

    }

}
