/* 
 * TODO LIST API
 *
 * exemple d'API REST avec de la documentation
 *
 * OpenAPI spec version: 1.00
 * Contact: frederic.Berton@capgemini.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TodoListApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class TodoListApiTests
    {
        private TodoListApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new TodoListApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TodoListApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' TodoListApi
            //Assert.IsInstanceOfType(typeof(TodoListApi), instance, "instance is a TodoListApi");
        }

        /// <summary>
        /// Test CreateTodoItem
        /// </summary>
        [Test]
        public void CreateTodoItemTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateOrUpdateTodoItem body = null;
            //instance.CreateTodoItem(body);
            
        }
        /// <summary>
        /// Test DeleteTodoItem
        /// </summary>
        [Test]
        public void DeleteTodoItemTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //instance.DeleteTodoItem(id);
            
        }
        /// <summary>
        /// Test GetTodoItem
        /// </summary>
        [Test]
        public void GetTodoItemTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.GetTodoItem(id);
            //Assert.IsInstanceOf<TodoItem> (response, "response is TodoItem");
        }
        /// <summary>
        /// Test GetTodoItems
        /// </summary>
        [Test]
        public void GetTodoItemsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetTodoItems();
            //Assert.IsInstanceOf<List<TodoItem>> (response, "response is List<TodoItem>");
        }
        /// <summary>
        /// Test UpdateTodoItem
        /// </summary>
        [Test]
        public void UpdateTodoItemTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //CreateOrUpdateTodoItem body = null;
            //instance.UpdateTodoItem(id, body);
            
        }
    }

}
