// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using Azure.Core;

namespace TodoListAPI
{
    /// <summary> Client options for TodoListAPIClient. </summary>
    public partial class TodoListAPIClientOptions : ClientOptions
    {
        private const ServiceVersion LatestVersion = ServiceVersion.V1_00;

        /// <summary> The version of the service to use. </summary>
        public enum ServiceVersion
        {
            /// <summary> Service version "1.00". </summary>
            V1_00 = 1,
        }

        internal string Version { get; }

        /// <summary> Initializes new instance of TodoListAPIClientOptions. </summary>
        public TodoListAPIClientOptions(ServiceVersion version = LatestVersion)
        {
            Version = version switch
            {
                ServiceVersion.V1_00 => "1.00",
                _ => throw new NotSupportedException()
            };
        }
    }
}
